// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = function(Liquid) {
    var Comment, _ref;
    Comment = (function(_super) {
      __extends(Comment, _super);

      function Comment() {
        _ref = Comment.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Comment.prototype.render = function(context) {
        return "";
      };

      return Comment;

    })(Liquid.Block);
    return Liquid.Template.registerTag("comment", Comment);
  };

}).call(this);
