// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = function(Liquid) {
    var Decrement;
    Decrement = (function(_super) {
      __extends(Decrement, _super);

      function Decrement(tagName, markup, tokens) {
        this.variable = markup.trim();
        Decrement.__super__.constructor.call(this, tagName, markup, tokens);
      }

      Decrement.prototype.render = function(context) {
        var value, _base, _name;
        value = (_base = context.scopes[0])[_name = this.variable] || (_base[_name] = 0);
        value = value - 1;
        context.scopes[0][this.variable] = value;
        return value.toString();
      };

      return Decrement;

    })(Liquid.Tag);
    return Liquid.Template.registerTag("decrement", Decrement);
  };

}).call(this);
