// Generated by CoffeeScript 1.6.3
(function() {
  var Include, Liquid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Liquid = require('../../liquid');

  Include = (function(_super) {
    var Syntax;

    __extends(Include, _super);

    Syntax = RegExp("(" + Liquid.StrictQuotedFragment.source + ")(\\s+(?:with|for)\\s+(" + Liquid.StrictQuotedFragment.source + "))?");

    function Include(tag, markup, tokens) {
      var $,
        _this = this;
      if ($ = markup.match(Syntax)) {
        this.templateName = $[1];
        this.variableName = $[3];
        this.attributes = {};
        markup.replace(Liquid.TagAttributes, function(key, value) {
          var _ref;
          _ref = key.split(':'), key = _ref[0], value = _ref[1];
          return _this.attributes[key] = value;
        });
      } else {
        throw new Liquid.SyntaxError("Error in tag 'include' - Valid syntax: include '[template]' (with|for) [object|collection]");
      }
      Include.__super__.constructor.call(this, tag, markup, tokens);
    }

    Include.prototype.render = function(context) {
      var output, partial, source, variable,
        _this = this;
      source = Include.readTemplateFromFileSystem(context, this.templateName);
      partial = Liquid.Template.parse(source);
      variable = context.get(this.variableName || this.templateName.slice(1, -1));
      output = '';
      context.stack(function() {
        var key, v, value, _i, _len, _ref, _results;
        _ref = _this.attributes;
        for (key in _ref) {
          value = _ref[key];
          context.set(key, context.get(value));
        }
        if (variable instanceof Array) {
          output = '';
          _results = [];
          for (_i = 0, _len = variable.length; _i < _len; _i++) {
            v = variable[_i];
            context.set(_this.templateName.slice(1, -1), v);
            _results.push(output += partial.render(context));
          }
          return _results;
        } else {
          context.set(_this.templateName.slice(1, -1), variable);
          return output = partial.render(context);
        }
      });
      return output;
    };

    Include.readTemplateFromFileSystem = function(context, templateName) {
      var fileSystem;
      fileSystem = context.registers.fileSystem || Liquid.Template.fileSystem;
      return fileSystem.readTemplateFile(context.get(templateName));
    };

    return Include;

  })(Liquid.Tag);

  Liquid.Template.registerTag("include", Include);

}).call(this);
