// Generated by CoffeeScript 1.6.3
(function() {
  var Liquid, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Liquid = require('../../liquid');

  Liquid.Tags.Unless = (function(_super) {
    __extends(Unless, _super);

    function Unless() {
      _ref = Unless.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Unless.prototype.render = function(context) {
      var output,
        _this = this;
      output = '';
      context.stack(function() {
        var block, _i, _len, _ref1;
        block = _this.blocks[0];
        if (!block.evaluate(context)) {
          output = _this.renderAll(block.attachment, context);
          return;
        }
        _ref1 = _this.blocks.slice(1);
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          block = _ref1[_i];
          if (block.evaluate(context)) {
            output = _this.renderAll(block.attachment, context);
            return;
          }
        }
        return '';
      });
      return output;
    };

    return Unless;

  })(Liquid.Tags.If);

  Liquid.Template.registerTag("unless", Liquid.Tags.Unless);

}).call(this);
