// Generated by CoffeeScript 1.6.3
(function() {
  var Liquid, fs, lv;

  fs = require('fs');

  Liquid = require('../liquid');

  Liquid.LiquidView = (function() {
    var cache;

    function LiquidView() {}

    cache = {};

    LiquidView.prototype.render = function($source, $data) {
      var $template;
      if ($data == null) {
        $data = {};
      }
      if (cache[$source] != null) {
        $template = cache[$source];
      } else {
        $template = Liquid.Template.parse($source);
      }
      return $template.render($data);
    };

    LiquidView.prototype.renderFile = function($path, $data, $next) {
      var _this = this;
      return fs.readFile($path, function($err, $source) {
        if ($err != null) {
          return $next($err);
        }
        return $next(null, _this.render($source, $data));
      });
    };

    return LiquidView;

  })();

  lv = new Liquid.LiquidView;

  module.exports = {
    __express: lv.renderFile,
    render: lv.render,
    renderFile: lv.renderFile
  };

}).call(this);
