// Generated by CoffeeScript 1.6.3
(function() {
  var Liquid;

  module.exports = Liquid = {
    VERSION: require('../package.json').version,
    Utils: (require('./liquid/utils'))(Liquid),
    Drop: (require('./liquid/drop'))(Liquid),
    Strainer: (require('./liquid/strainer'))(Liquid),
    Context: (require('./liquid/context'))(Liquid),
    Tag: (require('./liquid/tag'))(Liquid),
    Block: (require('./liquid/block'))(Liquid),
    Document: (require('./liquid/document'))(Liquid),
    Variable: (require('./liquid/variable'))(Liquid),
    BlankFileSystem: (require('./liquid/blankfilesystem'))(Liquid),
    LocalFileSystem: (require('./liquid/localfilesystem'))(Liquid),
    Template: (require('./liquid/template'))(Liquid),
    StandardFilters: (require('./liquid/standardfilters'))(Liquid),
    Condition: (require('./liquid/condition'))(Liquid),
    ElseCondition: (require('./liquid/elsecondition'))(Liquid),
    Assign: (require('./liquid/tags/assign'))(Liquid),
    Tags: {
      Capture: (require('./liquid/tags/capture'))(Liquid),
      Case: (require('./liquid/tags/case'))(Liquid),
      Comment: (require('./liquid/tags/comment'))(Liquid),
      Cycle: (require('./liquid/tags/cycle'))(Liquid),
      Decrement: (require('./liquid/tags/decrement'))(Liquid),
      For: (require('./liquid/tags/for'))(Liquid),
      If: (require('./liquid/tags/if'))(Liquid),
      IfChanged: (require('./liquid/tags/ifchanged'))(Liquid),
      Include: (require('./liquid/tags/include'))(Liquid),
      Increment: (require('./liquid/tags/increment'))(Liquid),
      Unless: (require('./liquid/tags/unless'))(Liquid)
    }
  };

}).call(this);
