// Generated by CoffeeScript 1.6.3
(function() {
  var Liquid,
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Liquid = require('../liquid');

  Liquid.Context = (function() {
    var LITERALS, compact, flatten;

    LITERALS = {
      'nil': null,
      'null': null,
      '': null,
      'true': true,
      'false': false
    };

    compact = function($this) {
      var $that, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = $this.length; _i < _len; _i++) {
        $that = $this[_i];
        if ($that) {
          _results.push($that);
        }
      }
      return _results;
    };

    flatten = function($list) {
      var $a, $item, _i, _len;
      if ($list == null) {
        return [];
      }
      $a = [];
      for (_i = 0, _len = $list.length; _i < _len; _i++) {
        $item = $list[_i];
        if (Array.isArray($item)) {
          $a = $a.concat(flatten($item));
        } else {
          $a.push($item);
        }
      }
      return $a;
    };

    function Context(environments, outerScope, registers, rethrowErrors, resourceLimits) {
      var _base, _base1;
      if (environments == null) {
        environments = {};
      }
      if (outerScope == null) {
        outerScope = {};
      }
      if (registers == null) {
        registers = {};
      }
      if (rethrowErrors == null) {
        rethrowErrors = false;
      }
      if (resourceLimits == null) {
        resourceLimits = {};
      }
      this.environments = flatten([environments]);
      this.scopes = [outerScope || {}];
      this.registers = registers;
      this.errors = [];
      this.rethrowErrors = rethrowErrors;
      this.resourceLimits = resourceLimits;
      (_base = this.resourceLimits).renderScoreCurrent || (_base.renderScoreCurrent = 0);
      (_base1 = this.resourceLimits).assignScoreCurrent || (_base1.assignScoreCurrent = 0);
      this.interrupts = [];
      this.filters = [];
      this.strainer = Liquid.Strainer.create(this);
      this.squashInstanceAssignsWithEnvironments();
    }

    Context.prototype.resourceLimitsReached = function() {
      return (this.resourceLimits.renderLengthLimit && this.resourceLimits.renderLengthCurrent > this.resourceLimits.renderLengthLimit) || (this.resourceLimits.renderScoreLimit && this.resourceLimits.renderScoreCurrent > this.resourceLimits.renderScoreLimit) || (this.resourceLimits.assignScoreLimit && this.resourceLimits.assignScoreCurrent > this.resourceLimits.assignScoreLimit);
    };

    Context.prototype.addFilters = function(filters) {
      var f, _i, _j, _len, _len1, _results;
      filters = compact(flatten([filters]));
      for (_i = 0, _len = filters.length; _i < _len; _i++) {
        f = filters[_i];
        if (typeof f !== "function") {
          throw Liquid.ArgumentError("Expected module but got: " + typeof f);
        }
        this.strainer.addKnownFilter(f);
      }
      if (this.strainer) {
        _results = [];
        for (_j = 0, _len1 = filters.length; _j < _len1; _j++) {
          f = filters[_j];
          _results.push(strainer.extend(f));
        }
        return _results;
      } else {
        return this.filters.concat(filters);
      }
    };

    Context.prototype.hasInterrupt = function() {
      return this.interrupts.any();
    };

    Context.prototype.pushInterrupt = function(e) {
      return this.interrupts.push(e);
    };

    Context.prototype.popInterrupt = function() {
      return this.interrupts.pop();
    };

    Context.prototype.handleError = function(e) {
      this.errors.push(e);
      if (this.rethrowErrors) {
        if (e instanceof Liquid.SyntaxError) {
          throw "Liquid syntax error: " + e.message;
        } else {
          throw "Liquid error: " + e.message;
        }
      }
    };

    Context.prototype.invoke = function() {
      var args, method, _ref;
      method = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return (_ref = this.strainer).invoke.apply(_ref, [method].concat(__slice.call(args)));
    };

    Context.prototype.push = function(newScope) {
      if (newScope == null) {
        newScope = {};
      }
      this.scopes.unshift(newScope);
      if (this.scopes.length > 100) {
        throw new Liquid.StackLevelError("Nesting too deep");
      }
    };

    Context.prototype.merge = function(newScope) {
      var key, val, _results;
      _results = [];
      for (key in newScope) {
        val = newScope[key];
        _results.push(this.scopes[0][key] = val);
      }
      return _results;
    };

    Context.prototype.pop = function() {
      if (this.scopes.length === 1) {
        throw new Liquid.ContextError();
      }
      return this.scopes.shift();
    };

    Context.prototype.stack = function($yield, newScope) {
      if (newScope == null) {
        newScope = {};
      }
      this.push(newScope);
      try {
        return $yield();
      } finally {
        this.pop();
      }
    };

    Context.prototype.clearInstanceAssigns = function() {
      return this.scopes[0] = {};
    };

    Context.prototype.get = function(varname) {
      return this.resolve(varname);
    };

    Context.prototype.set = function(varname, value) {
      return this.scopes[0][varname] = value;
    };

    Context.prototype.hasKey = function(key) {
      return this.resolve(key) != null;
    };

    Context.prototype.resolve = function(key) {
      var $, ch, _i, _j, _ref, _ref1, _ref2, _ref3, _results, _results1;
      if (LITERALS[key] != null) {
        return LITERALS[key];
      } else {
        if ($ = /^'(.*)'$/.exec(key)) {
          return $[1];
        } else if ($ = /^"(.*)"$/.exec(key)) {
          return $[1];
        } else if ($ = /^(\d+)$/.exec(key)) {
          return parseInt($[1], 10);
        } else if ($ = /^(\d[\d\.]+)$/.exec(key)) {
          return parseFloat($[1]);
        } else if ($ = /^\((\S+)\.\.(\S+)\)$/.exec(key)) {
          if (isNaN($[1])) {
            _results = [];
            for (ch = _i = _ref = $[1].charCodeAt(0), _ref1 = $[2].charCodeAt(0); _ref <= _ref1 ? _i <= _ref1 : _i >= _ref1; ch = _ref <= _ref1 ? ++_i : --_i) {
              _results.push(String.fromCharCode(ch));
            }
            return _results;
          } else {
            return (function() {
              _results1 = [];
              for (var _j = _ref2 = parseInt($[1]), _ref3 = parseInt($[2]); _ref2 <= _ref3 ? _j <= _ref3 : _j >= _ref3; _ref2 <= _ref3 ? _j++ : _j--){ _results1.push(_j); }
              return _results1;
            }).apply(this);
          }
        } else {
          return this.variable(key);
        }
      }
    };

    Context.prototype.findVariable = function(key) {
      var e, s, scope, variable, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.scopes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        s = _ref[_i];
        if (s[key] != null) {
          scope = s;
        }
      }
      if (scope == null) {
        _ref1 = this.environments;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          e = _ref1[_j];
          if (variable = this.lookupAndEvaluate(e, key)) {
            scope = e;
            break;
          }
        }
      }
      scope || (scope = this.environments[this.environments.length - 1] || this.scopes[this.scopes.length - 1]);
      variable || (variable = this.lookupAndEvaluate(scope, key));
      if (variable != null) {
        if (typeof variable.context === "function") {
          variable.context(this);
        }
      }
      return variable;
    };

    Context.prototype.variable = function(markup) {
      var $, firstPart, object, part, parts, squareBracketed, _i, _len;
      if (typeof markup !== "string") {
        return null;
      }
      parts = markup.match(/\[[^\]]+\]|(?:[\w\-]\??)+/g);
      squareBracketed = /^\[(.*)\]$/;
      firstPart = parts.shift();
      if (($ = squareBracketed.exec(firstPart))) {
        firstPart = this.resolve($[1]);
      }
      if (object = this.findVariable(firstPart)) {
        for (_i = 0, _len = parts.length; _i < _len; _i++) {
          part = parts[_i];
          if (($ = squareBracketed.exec(part))) {
            part = this.resolve($[1]);
            object = object[part];
          } else {
            if (typeof object === 'object' && part in object) {
              object = this.lookupAndEvaluate(object, part);
            } else if (/^\d+$/.test(part)) {
              object = object[parseInt(part, 10)];
            } else {
              return null;
            }
          }
          if (object != null) {
            if (typeof object.context === "function") {
              object.context(this);
            }
          }
        }
      }
      return object;
    };

    Context.prototype.lookupAndEvaluate = function(obj, key) {
      var value;
      if (typeof (value = obj[key]) === 'function') {
        return obj[key] = value(this);
      } else {
        return value;
      }
    };

    Context.prototype.squashInstanceAssignsWithEnvironments = function() {
      var env, k, last, _results;
      last = this.scopes.length - 1;
      _results = [];
      for (k in this.scopes[last]) {
        _results.push((function() {
          var _i, _len, _results1;
          _results1 = [];
          for (_i = 0, _len = environments.length; _i < _len; _i++) {
            env = environments[_i];
            if (__indexOf.call(env, k) >= 0) {
              _results1.push(this.scopes[last][k] = this.lookupAndEvaluate(env, k));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return Context;

  })();

}).call(this);
