// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(Liquid) {
    var BlankFileSystem;
    return BlankFileSystem = (function() {
      function BlankFileSystem() {}

      BlankFileSystem.prototype.readTemplateFile = function(path) {
        throw "This liquid context does not allow includes.";
      };

      return BlankFileSystem;

    })();
  };

}).call(this);
