// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = function(Liquid) {
    var Document;
    return Document = (function(_super) {
      __extends(Document, _super);

      function Document(tokens) {
        this.blockDelimiter = [];
        this.parse(tokens);
      }

      Document.prototype.assertMissingDelimitation = function() {};

      return Document;

    })(Liquid.Block);
  };

}).call(this);
