// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(Liquid) {
    var Drop;
    return Drop = (function() {
      function Drop() {}

      Drop.prototype.setContext = function(context) {
        return this.context = context;
      };

      Drop.prototype.beforeMethod = function(method) {};

      Drop.prototype.invokeDrop = function(method) {
        var results;
        results = this.beforeMethod();
        if (!results && (method in this)) {
          results = this[method].apply(this);
        }
        return results;
      };

      Drop.prototype.hasKey = function(name) {
        return true;
      };

      return Drop;

    })();
  };

}).call(this);
