// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = function(Liquid) {
    var ElseCondition, _ref;
    return ElseCondition = (function(_super) {
      __extends(ElseCondition, _super);

      function ElseCondition() {
        _ref = ElseCondition.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ElseCondition.prototype.isElse = true;

      ElseCondition.prototype.evaluate = function(context) {
        return true;
      };

      ElseCondition.prototype.toString = function() {
        return "<ElseCondition>";
      };

      return ElseCondition;

    })(Liquid.Condition);
  };

}).call(this);
