// Generated by CoffeeScript 1.6.3
(function() {
  Object.defineProperties(Array, {
    inject: {
      value: function($this, $memo, $func) {
        var $that, _i, _len;
        for (_i = 0, _len = $this.length; _i < _len; _i++) {
          $that = $this[_i];
          $memo = $func.call($this, $memo, $that);
        }
        return $memo;
      }
    }
  });

  Object.defineProperties(Array.prototype, {
    inject: {
      value: function($memo, $func) {
        return Array.inject(this, $memo, $func);
      }
    }
  });

}).call(this);
