// Generated by CoffeeScript 1.6.3
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  module.exports = function(Liquid) {
    var LocalFileSystem;
    return LocalFileSystem = (function() {
      function LocalFileSystem(root) {
        this.root = root;
      }

      LocalFileSystem.prototype.readTemplateFile = function($template) {
        return String(fs.readFileSync(path.resolve(this.root, $template)));
      };

      return LocalFileSystem;

    })();
  };

}).call(this);
