// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  module.exports = function(Liquid) {
    var Strainer;
    return Strainer = (function() {
      Strainer.filters = {};

      Strainer.globalFilter = function(filters) {
        var f, _results;
        _results = [];
        for (f in filters) {
          _results.push(Strainer.filters[f] = filters[f]);
        }
        return _results;
      };

      Strainer.requiredMethods = ["respondTo", "context"];

      Strainer.create = function(context) {
        var f, strainer;
        strainer = new Strainer(context);
        for (f in Strainer.filters) {
          strainer[f] = Strainer.filters[f];
        }
        return strainer;
      };

      function Strainer(context) {
        this.context = context;
      }

      Strainer.prototype.respondTo = function(methodName) {
        methodName = methodName.toString();
        if (methodName.match(/^__/)) {
          return false;
        }
        if (__indexOf.call(Strainer.requiredMethods, methodName) >= 0) {
          return false;
        }
        if (this[methodName] != null) {
          return true;
        } else {
          return false;
        }
      };

      return Strainer;

    })();
  };

}).call(this);
