// Generated by CoffeeScript 1.6.3
(function() {
  var Liquid,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Liquid = require('../liquid');

  Liquid.Strainer = (function() {
    var INTERNAL_METHOD;

    INTERNAL_METHOD = /^__/;

    Strainer.requiredMethods = ["respondTo", "context"];

    Strainer.filters = {};

    function Strainer(context) {
      this.context = context;
    }

    Strainer.globalFilter = function(filter) {
      if ('function' !== typeof filter) {
        throw ArgumentError("Passed filter is not a module");
      }
      return Strainer.filters[filter.name] = filter;
    };

    Strainer.create = function(context) {
      var func, k, m, name, strainer, _ref;
      strainer = new Strainer(context);
      _ref = Strainer.filters;
      for (k in _ref) {
        m = _ref[k];
        for (name in m) {
          func = m[name];
          strainer[name] = func;
        }
      }
      return strainer;
    };

    Strainer.prototype.respondTo = function(methodName) {
      methodName = methodName.toString();
      if (INTERNAL_METHOD.test(methodName)) {
        return false;
      }
      if (__indexOf.call(Strainer.requiredMethods, methodName) >= 0) {
        return false;
      }
      if (this[methodName] != null) {
        return true;
      } else {
        return false;
      }
    };

    Strainer.prototype.extend = function(m) {
      var name, val, _results;
      _results = [];
      for (name in m) {
        val = m[name];
        if (this[name] == null) {
          _results.push(this[name] = val);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Strainer;

  })();

}).call(this);
