// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(Liquid) {
    var Tag;
    return Tag = (function() {
      function Tag(tagName, markup, tokens) {
        this.tagName = tagName;
        this.markup = markup;
        this.nodelist = this.nodelist || [];
        this.parse(tokens);
      }

      Tag.prototype.parse = function(tokens) {};

      Tag.prototype.render = function(context) {
        return "";
      };

      return Tag;

    })();
  };

}).call(this);
