// Generated by CoffeeScript 1.8.0
(function() {
  var compact, flatten;

  compact = function($this) {
    var $that, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = $this.length; _i < _len; _i++) {
      $that = $this[_i];
      if ($that) {
        _results.push($that);
      }
    }
    return _results;
  };

  flatten = function($list) {
    var $a, $item, _i, _len;
    if ($list == null) {
      return [];
    }
    $a = [];
    for (_i = 0, _len = $list.length; _i < _len; _i++) {
      $item = $list[_i];
      if (Array.isArray($item)) {
        $a = $a.concat(flatten($item));
      } else {
        $a.push($item);
      }
    }
    return $a;
  };

  module.exports = {
    compact: compact,
    flatten: flatten
  };

}).call(this);
