// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(Liquid) {
    var flatten;
    return {
      flatten: flatten = function($list) {
        var $a, $item, _i, _len;
        if ($list == null) {
          return [];
        }
        $a = [];
        for (_i = 0, _len = $list.length; _i < _len; _i++) {
          $item = $list[_i];
          if (Array.isArray($item)) {
            $a = $a.concat(flatten($item));
          } else {
            $a.push($item);
          }
        }
        return $a;
      }
    };
  };

}).call(this);
